source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
## ignore warning
inhibit_all_warnings!
target 'WeChat' do
#YYKit
#pod 'YYKit'                             , '1.0.9'
# YYKit 的一套分类
pod 'YYCategories'                      , '1.0.4'
# 富文本
pod 'YYText'                            , '1.0.7'
# 字典转模型
pod 'YYModel'                           , '1.0.4'
# YYImage
pod 'YYImage'                           , '1.0.4'
# webP
pod 'YYImage/WebP'
# 高性能的 iOS 缓存框架
pod 'YYCache'                           , '1.0.4'
# 高性能的 iOS 异步图像加载框架。
pod 'YYWebImage'                        , '1.0.5'
# iOS 键盘监听管理工具
pod 'YYKeyboardManager'                 , '1.0.1'
# iOS 全局并发队列管理工具
pod 'YYDispatchQueuePool'               , '1.0'
# iOS 异步绘制与显示的工具
pod 'YYAsyncLayer'                      , '1.0'

# AutoLayout
pod 'Masonry'                           , '1.0.2'

# 缓存tableViewCell的高度
pod 'UITableView+FDTemplateLayoutCell'  , '1.6'
# IB View自动收缩
# pod 'UIView+FDCollapsibleConstraints'   , '1.1'
# 侧滑手势
pod 'FDFullscreenPopGesture'            , '1.1'
# 字典转模型 该项目使用YYModel
pod 'MJExtension'                       , '3.0.13'
pod 'MJRefresh'                         , '3.1.12'
# 加密
pod 'CocoaSecurity'                     , '1.2.4'

# 颜色分类
pod 'Colours'                           , '5.13.0'

# 根据颜色 生成一张图片
pod 'UIImage+ImageWithColor'            , '1.4.0'

# HUD
pod 'MBProgressHUD'                     , '1.1.0'
pod 'SVProgressHUD'                     , '2.1.2'
# 状态栏通知
pod 'JDStatusBarNotification'           , '1.5.5'

# 数据库
pod 'FMDB'                              , '2.6.2'

# 环形进度条
pod 'DACircularProgress'                , '2.3.1'

# 消息链
# pod 'ReactiveCocoa'                     ,'2.5'
# 适配Xcode9.0 iOS 11
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
# 网络请求
pod 'AFNetworking'                      , '3.1.0'

# 图片缓存
pod 'SDWebImage'                        , '4.0.0'

# UIView模糊
pod 'FXBlurView'                        , '1.6.4'

# WebSocket
pod 'SocketRocket'                      , '0.5.1'

# badgeValue
pod 'WZLBadge'                          , '1.2.6'
pod 'JSBadgeView'                       , '1.4.1'

# 文件压缩与解压
pod 'SSZipArchive'                      , '1.8.1'

# 钥匙串存储
pod 'SAMKeychain'                       , '1.5.2'

# 菊花activity
pod 'MMMaterialDesignSpinner', '0.2.3'

#FPS检测
pod 'JPFPSStatus', '0.1'

#打印一切
pod 'LxDBAnything', '1.1.0'

# view的圆角处理 避免离屏渲染
# pod 'JMRoundedCorner'                   , '1.2.1'
pod 'HYBImageCliped'                    , '2.2.4'
pod 'ZYCornerRadius'                    , '1.0.2'
pod 'HJCornerRadius', :git => 'https://github.com/panghaijiao/HJCornerRadius.git'

pod 'TTTAttributedLabel'                , '2.0.0'

#########  Category  #########
# 非常强大的Objective-C库的扩展
pod 'libextobjc'                        , '0.4.1'

# UI block
pod 'BlocksKit'                         , '2.2.5'
# UICollectionView左对齐布局
pod 'UICollectionViewLeftAlignedLayout' , '1.0.2'


# FaceBook KVO（优雅的代替系统原生的KVO）
pod 'KVOController'                     , '1.2.0'

# FaceBook 内存分析工具 其中包括了：FBAllocationTracker 和 FBRetainCycleDetector两个工具
pod 'FBMemoryProfiler'                  , '0.1.3'

# 二维码，条形码
pod 'LBXScan/LBXNative'                 ,'2.0'
pod 'LBXScan/LBXZXing'                  ,'2.0'
pod 'LBXScan/LBXZBar'                   ,'2.0'
pod 'LBXScan/UI'                        ,'2.0'

#######---------- 企业第三方 ------------------########
# 集成腾讯bugly，用于打包测试和bug异常收集
# pod 'Bugly'                             , '2.4.8'
# 极光推送
# pod 'JPush'                             , '3.0.6'
# 友盟相关
# pod 'UMengAnalytics-NO-IDFA'            , '4.2.5'
# U-Share SDK UI模块（分享面板，建议添加）
# pod 'UMengUShare/UI'                    , '6.4.5'
# 集成微信(完整版14.4M)
# pod 'UMengUShare/Social/WeChat'         , '6.4.5'
# 集成新浪微博(精简版1M)
# pod 'UMengUShare/Social/ReducedSina'    , '6.4.5'
# 集成QQ/QZone/TIM(精简版0.5M)
# pod 'UMengUShare/Social/ReducedQQ'      , '6.4.5'

# 高的定位地图
# pod 'AMapLocation'                      , '2.4.0'

# 文字滚动的label
pod 'TXScrollLabelView'                 , '1.3.1'

# iOS程序调试神器
# http://neater.github.io/blog/2014/07/31/flex!iosdiao-shi-li-qi/
# http://www.cocoachina.com/ios/20140728/9259.html
# http://www.starming.com/index.php?v=index&view=23
pod 'FLEX'                              , '2.4.0'

# pop动画
pod 'pop'                               , '1.0.10'
# 键盘管理
pod 'IQKeyboardManager'                 , '5.0.2'
# 瀑布流
pod 'CHTCollectionViewWaterfallLayout'  , '0.9.6'
# 选择器
pod 'ActionSheetPicker-3.0'             , '2.2.0'

# 空占位
pod 'DZNEmptyDataSet'                   , '1.8.1'
# 图片浏览器
#pod 'PYPhotoBrowser'                    , '1.5.0'
# 类似网易新闻的标签栏
#pod 'YZDisplayViewController', '1.0.6'
# 苹果内购
#pod 'RMStore', '0.7.1'

# SVG 展示
pod 'SVGKit'

target 'WeChatTests' do
end

target 'WeChatUITests' do
end

end

